server.port=8080

spring.main.allow-bean-definition-overriding=true

spring.jpa.open-in-view=false

# ===== SQL 
spring.sql.init.mode=never

# ===== PostgreSQL DataSource =====
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=e2m3

# ===== HikariCP
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10

# ===== MyBatis =====
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=org.egovframe.rte.psl.dataaccess.util
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL

# ===== AirKorea API =====
airkorea.serviceKey=affb13ee6ef3859b86baf46c78d234917b71bed163d62a4d99062aa7932dd280
#airkorea.serviceKey=085205408679d3d1e570b2d9c85f75ac47e6bca540d31f241e7217cf18f7da50
#airkorea.serviceKey=a76e0e945270993984da72cdccd7ca11566795343496f0c8371febaefe93089f
#airkorea.serviceKey=3462611d68e3ab97d52254bbfd03ce215aadcc431616ca705c9be9156ad333c4
#airkorea.serviceKey=47406d419997c9d0a06b624227b02c9e45e78f2d6bb12b9c1cb8b4e646158f11

airkorea.msrstn.baseUrl=http://apis.data.go.kr/B552584/MsrstnInfoInqireSvc
airkorea.arpltn.baseUrl=http://apis.data.go.kr/B552584/ArpltnInforInqireSvc

#VWorld-----------------------------
vworld.key=7A65FDA3-D178-3890-AE07-57EE2AC885F7
vworld.search.baseUrl=https://api.vworld.kr/req/search
