server.port=8080

# 수동 Bean이 자동 Bean을 오버라이딩하게 설정
spring.main.allow-bean-definition-overriding=true

# open-in-view false: 트랜잭션이 종료될 때 영속성 컨텍스트 종료
spring.jpa.open-in-view=false

# ===== SQL 초기화 비활성화 =====
spring.sql.init.mode=never

# ===== PostgreSQL DataSource =====
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=e2m3

# ===== MyBatis =====
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=org.egovframe.rte.psl.dataaccess.util
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL

# ===== AirKorea API =====
airkorea.serviceKey=71957e6f244645c518fa593a6fa52245832ae17d7c4b1c33f2e5aabd4ca09e1b
airkorea.msrstn.baseUrl=http://apis.data.go.kr/B552584/MsrstnInfoInqireSvc
airkorea.arpltn.baseUrl=http://apis.data.go.kr/B552584/ArpltnInforInqireSvc
